version: '3'
services:
  postgres:
    container_name: first-db
    image: "postgres:15"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: prlrelwx
      POSTGRES_USER: prlrelwx
      POSTGRES_PASSWORD: WIY7Sn4gxX22t1XBxlgeQNpqKfuS42r1
  web:
    container_name: simple-app
    build: .
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://rosie.db.elephantsql.com:5432/prlrelwx
      SPRING_DATASOURCE_USERNAME: prlrelwx
      SPRING_DATASOURCE_PASSWORD: WIY7Sn4gxX22t1XBxlgeQNpqKfuS42r1